server:
  host: "0.0.0.0"
  port: 8000
  debug: true

modules:
  core: true
  spotify: false
  weather:
    enabled: true
    default_location: "Toulouse"
  tts:
    enabled: true
    rate: 130        # Vitesse de parole en mots par minute (défaut: 150)
  surveillance: false
  alarms: false
